### ISSUE TITLE
AttributeError: 'Model' object has no attribute 'base_model_prefix'

### ISSUE THREAD

**Issue by ntuwork** [sunnweiwei/GenRet#1]
Hi, thanks for the great work and releasing the code. I get an error as fellows:

```
DR evaluation out/model-1/199.pt
## Model # new keys in file: [] # no match keys: []
(100, 768)
100%|███████████████████████████████████| 62/62 [00:03<00:00, 17.82it/s]
Doc_code balance {'Avg': 0.002729202926944896, 'Max': 0.002729202926944896, 'Min': 0.002729202926944896, 'Flat': 0.10003280511030721}
Doc_code conflict {'Max': 109739, 'Min': 109739, 'Type': 1, '%': 9.11253064088428e-06}
Kmeans balance {'Avg': 0.10003280511030721, 'Max': 0.10003280511030721, 'Min': 0.10003280511030721, 'Flat': 0.10003280511030721}
Kmeans conflict {'Max': 109739, 'Min': 109739, 'Type': 1, '%': 9.11253064088428e-06}
Test out/model-1/0.pt
## Model # new keys in file: [] # no match keys: []
100%|██████████████████████| 109739/109739 [00:00<00:00, 5565105.27it/s]
  0%|                                           | 0/245 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/GenRet/run.py", line 1230, in <module>
    main()
  File "/home/GenRet/run.py", line 1213, in main
    test(config)
  File "/home/GenRet/run.py", line 840, in test
    output = model.generate(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1485, in generate
    self._validate_model_kwargs(model_kwargs.copy())
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1230, in _validate_model_kwargs
    base_model = getattr(self, self.base_model_prefix, None)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Model' object has no attribute 'base_model_prefix'
```

How can I fix it? Thanks!

**Comment by yhy-2000** [comment]
I meet the same error, I guess it may be an issue related to the transformers version, which version do you use? @sunnweiwei

**Comment by sunnweiwei** [comment]
Hi, I am using transformers-4.28.0 and torch-1.13.0.

**Comment by ntuwork** [comment]
> Hi, I am using transformers-4.28.0 and torch-1.13.0.

OK, thanks.
One thing I noticed in the code is that there is a lot of commented code. These codes seem to be key steps in the GenRet implementation. They seem to be related to the different training stages of the model, e.g. ```code_logits = torch.stack(code_logits, dim=1)``` seems to be used for warmup, while ```code_logits = self.centroids(decoder_outputs)``` is used for formal training. There are also a lot of lossy computations that are commented out.

Can you provide some clarification please?

**Comment by sunnweiwei** [comment]
Hi,

Yes, there is a lot of commented-out code. This includes code used in experiments. I will do my best to clean up the code and add necessary explanations. Regarding `code_logits`: the line `code_logits = self.centroids(decoder_outputs)` is not used in any training stage.

**Comment by ntuwork** [comment]
> Hi,
> 
> Yes, there is a lot of commented-out code. This includes code used in experiments. I will do my best to clean up the code and add necessary explanations. Regarding `code_logits`: the line `code_logits = self.centroids(decoder_outputs)` is not used in any training stage.

OK, Thanks, Expectations Notes
