### ISSUE TITLE
The role of ```doc_code = [0] * len(corpus)```

### ISSUE THREAD

**Issue by ntuwork** [sunnweiwei/GenRet#5]
Thanks for sharing the code!
I have something confusing, in ```run.py``` at line 1010, this line ```doc_code = [0] * len(corpus)``` changes doc_code all the way to 0. Can you tell me what is the function of this step?

**Comment by sunnweiwei** [comment]
Hi, Sorry, this is the code for debugging and I forgot to delete it. I have updated the code. Thank you for pointing out this issue.
